stages:
  - build

job:
  stage: build
  script:
  - 'cd c:\CIbuild\holden'
  - echo "Restoring NuGet Packages..."
  - '"c:\nuget\nuget.exe" restore "C:\CIbuild\holden\HoldemHotshots\HoldemHotshots.sln"'
  - ''
  - echo "Release build..."
  - C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:detailed "C:\CIbuild\holden\HoldemHotshots\HoldemHotshots.sln"
  tags: 
  except:
  - tags